/*
Whop API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.10
Contact: support@whop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whopclient

import (
	"encoding/json"
)

// BanLicenseByKeyRequest struct for BanLicenseByKeyRequest
type BanLicenseByKeyRequest struct {
	Metadata *UpdateLicenseByKeyRequestMetadata `json:"metadata,omitempty"`
}

// NewBanLicenseByKeyRequest instantiates a new BanLicenseByKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBanLicenseByKeyRequest() *BanLicenseByKeyRequest {
	this := BanLicenseByKeyRequest{}
	return &this
}

// NewBanLicenseByKeyRequestWithDefaults instantiates a new BanLicenseByKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBanLicenseByKeyRequestWithDefaults() *BanLicenseByKeyRequest {
	this := BanLicenseByKeyRequest{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *BanLicenseByKeyRequest) GetMetadata() UpdateLicenseByKeyRequestMetadata {
	if o == nil || o.Metadata == nil {
		var ret UpdateLicenseByKeyRequestMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BanLicenseByKeyRequest) GetMetadataOk() (*UpdateLicenseByKeyRequestMetadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *BanLicenseByKeyRequest) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given UpdateLicenseByKeyRequestMetadata and assigns it to the Metadata field.
func (o *BanLicenseByKeyRequest) SetMetadata(v UpdateLicenseByKeyRequestMetadata) {
	o.Metadata = &v
}

func (o BanLicenseByKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return json.Marshal(toSerialize)
}

type NullableBanLicenseByKeyRequest struct {
	value *BanLicenseByKeyRequest
	isSet bool
}

func (v NullableBanLicenseByKeyRequest) Get() *BanLicenseByKeyRequest {
	return v.value
}

func (v *NullableBanLicenseByKeyRequest) Set(val *BanLicenseByKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBanLicenseByKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBanLicenseByKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBanLicenseByKeyRequest(val *BanLicenseByKeyRequest) *NullableBanLicenseByKeyRequest {
	return &NullableBanLicenseByKeyRequest{value: val, isSet: true}
}

func (v NullableBanLicenseByKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBanLicenseByKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


