/*
Whop API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.10
Contact: support@whop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whopclient

import (
	"encoding/json"
)

// ConfirmProductResponse struct for ConfirmProductResponse
type ConfirmProductResponse struct {
	Confirmation NullableString `json:"confirmation,omitempty"`
}

// NewConfirmProductResponse instantiates a new ConfirmProductResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfirmProductResponse() *ConfirmProductResponse {
	this := ConfirmProductResponse{}
	return &this
}

// NewConfirmProductResponseWithDefaults instantiates a new ConfirmProductResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfirmProductResponseWithDefaults() *ConfirmProductResponse {
	this := ConfirmProductResponse{}
	return &this
}

// GetConfirmation returns the Confirmation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfirmProductResponse) GetConfirmation() string {
	if o == nil || o.Confirmation.Get() == nil {
		var ret string
		return ret
	}
	return *o.Confirmation.Get()
}

// GetConfirmationOk returns a tuple with the Confirmation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfirmProductResponse) GetConfirmationOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Confirmation.Get(), o.Confirmation.IsSet()
}

// HasConfirmation returns a boolean if a field has been set.
func (o *ConfirmProductResponse) HasConfirmation() bool {
	if o != nil && o.Confirmation.IsSet() {
		return true
	}

	return false
}

// SetConfirmation gets a reference to the given NullableString and assigns it to the Confirmation field.
func (o *ConfirmProductResponse) SetConfirmation(v string) {
	o.Confirmation.Set(&v)
}
// SetConfirmationNil sets the value for Confirmation to be an explicit nil
func (o *ConfirmProductResponse) SetConfirmationNil() {
	o.Confirmation.Set(nil)
}

// UnsetConfirmation ensures that no value is present for Confirmation, not even an explicit nil
func (o *ConfirmProductResponse) UnsetConfirmation() {
	o.Confirmation.Unset()
}

func (o ConfirmProductResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Confirmation.IsSet() {
		toSerialize["confirmation"] = o.Confirmation.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableConfirmProductResponse struct {
	value *ConfirmProductResponse
	isSet bool
}

func (v NullableConfirmProductResponse) Get() *ConfirmProductResponse {
	return v.value
}

func (v *NullableConfirmProductResponse) Set(val *ConfirmProductResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConfirmProductResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConfirmProductResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfirmProductResponse(val *ConfirmProductResponse) *NullableConfirmProductResponse {
	return &NullableConfirmProductResponse{value: val, isSet: true}
}

func (v NullableConfirmProductResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfirmProductResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


