/*
Whop API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.10
Contact: support@whop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whopclient

import (
	"encoding/json"
)

// CreateLinkRequest struct for CreateLinkRequest
type CreateLinkRequest struct {
	// Product ID to associate this link with.
	ProductId *int64 `json:"product_id,omitempty"`
	// Password to protect the link with.
	Password *string `json:"password,omitempty"`
	// Amount of stock to make available via. the link.
	Stock *int64 `json:"stock,omitempty"`
	// Array of discord acconut IDs.
	DiscordIds *[]string `json:"discord_ids,omitempty"`
}

// NewCreateLinkRequest instantiates a new CreateLinkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLinkRequest() *CreateLinkRequest {
	this := CreateLinkRequest{}
	return &this
}

// NewCreateLinkRequestWithDefaults instantiates a new CreateLinkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLinkRequestWithDefaults() *CreateLinkRequest {
	this := CreateLinkRequest{}
	return &this
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *CreateLinkRequest) GetProductId() int64 {
	if o == nil || o.ProductId == nil {
		var ret int64
		return ret
	}
	return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLinkRequest) GetProductIdOk() (*int64, bool) {
	if o == nil || o.ProductId == nil {
		return nil, false
	}
	return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *CreateLinkRequest) HasProductId() bool {
	if o != nil && o.ProductId != nil {
		return true
	}

	return false
}

// SetProductId gets a reference to the given int64 and assigns it to the ProductId field.
func (o *CreateLinkRequest) SetProductId(v int64) {
	o.ProductId = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *CreateLinkRequest) GetPassword() string {
	if o == nil || o.Password == nil {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLinkRequest) GetPasswordOk() (*string, bool) {
	if o == nil || o.Password == nil {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *CreateLinkRequest) HasPassword() bool {
	if o != nil && o.Password != nil {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *CreateLinkRequest) SetPassword(v string) {
	o.Password = &v
}

// GetStock returns the Stock field value if set, zero value otherwise.
func (o *CreateLinkRequest) GetStock() int64 {
	if o == nil || o.Stock == nil {
		var ret int64
		return ret
	}
	return *o.Stock
}

// GetStockOk returns a tuple with the Stock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLinkRequest) GetStockOk() (*int64, bool) {
	if o == nil || o.Stock == nil {
		return nil, false
	}
	return o.Stock, true
}

// HasStock returns a boolean if a field has been set.
func (o *CreateLinkRequest) HasStock() bool {
	if o != nil && o.Stock != nil {
		return true
	}

	return false
}

// SetStock gets a reference to the given int64 and assigns it to the Stock field.
func (o *CreateLinkRequest) SetStock(v int64) {
	o.Stock = &v
}

// GetDiscordIds returns the DiscordIds field value if set, zero value otherwise.
func (o *CreateLinkRequest) GetDiscordIds() []string {
	if o == nil || o.DiscordIds == nil {
		var ret []string
		return ret
	}
	return *o.DiscordIds
}

// GetDiscordIdsOk returns a tuple with the DiscordIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLinkRequest) GetDiscordIdsOk() (*[]string, bool) {
	if o == nil || o.DiscordIds == nil {
		return nil, false
	}
	return o.DiscordIds, true
}

// HasDiscordIds returns a boolean if a field has been set.
func (o *CreateLinkRequest) HasDiscordIds() bool {
	if o != nil && o.DiscordIds != nil {
		return true
	}

	return false
}

// SetDiscordIds gets a reference to the given []string and assigns it to the DiscordIds field.
func (o *CreateLinkRequest) SetDiscordIds(v []string) {
	o.DiscordIds = &v
}

func (o CreateLinkRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ProductId != nil {
		toSerialize["product_id"] = o.ProductId
	}
	if o.Password != nil {
		toSerialize["password"] = o.Password
	}
	if o.Stock != nil {
		toSerialize["stock"] = o.Stock
	}
	if o.DiscordIds != nil {
		toSerialize["discord_ids"] = o.DiscordIds
	}
	return json.Marshal(toSerialize)
}

type NullableCreateLinkRequest struct {
	value *CreateLinkRequest
	isSet bool
}

func (v NullableCreateLinkRequest) Get() *CreateLinkRequest {
	return v.value
}

func (v *NullableCreateLinkRequest) Set(val *CreateLinkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLinkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLinkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLinkRequest(val *CreateLinkRequest) *NullableCreateLinkRequest {
	return &NullableCreateLinkRequest{value: val, isSet: true}
}

func (v NullableCreateLinkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLinkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


