/*
Whop API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.10
Contact: support@whop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whopclient

import (
	"encoding/json"
)

// SendPushNotificationResponse struct for SendPushNotificationResponse
type SendPushNotificationResponse struct {
	Message NullableString `json:"message,omitempty"`
}

// NewSendPushNotificationResponse instantiates a new SendPushNotificationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendPushNotificationResponse() *SendPushNotificationResponse {
	this := SendPushNotificationResponse{}
	return &this
}

// NewSendPushNotificationResponseWithDefaults instantiates a new SendPushNotificationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendPushNotificationResponseWithDefaults() *SendPushNotificationResponse {
	this := SendPushNotificationResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SendPushNotificationResponse) GetMessage() string {
	if o == nil || o.Message.Get() == nil {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SendPushNotificationResponse) GetMessageOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *SendPushNotificationResponse) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *SendPushNotificationResponse) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *SendPushNotificationResponse) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *SendPushNotificationResponse) UnsetMessage() {
	o.Message.Unset()
}

func (o SendPushNotificationResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableSendPushNotificationResponse struct {
	value *SendPushNotificationResponse
	isSet bool
}

func (v NullableSendPushNotificationResponse) Get() *SendPushNotificationResponse {
	return v.value
}

func (v *NullableSendPushNotificationResponse) Set(val *SendPushNotificationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSendPushNotificationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSendPushNotificationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendPushNotificationResponse(val *SendPushNotificationResponse) *NullableSendPushNotificationResponse {
	return &NullableSendPushNotificationResponse{value: val, isSet: true}
}

func (v NullableSendPushNotificationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendPushNotificationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


