/*
Whop API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.10
Contact: support@whop.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whopclient

import (
	"encoding/json"
)

// SendPushNotificationRequest struct for SendPushNotificationRequest
type SendPushNotificationRequest struct {
	// The title to be displayed on the push notification.
	Title *string `json:"title,omitempty"`
	// The link to be displayed on the push notification.
	Link *string `json:"link,omitempty"`
	// The body text to display on the push notification.
	Body *string `json:"body,omitempty"`
}

// NewSendPushNotificationRequest instantiates a new SendPushNotificationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendPushNotificationRequest() *SendPushNotificationRequest {
	this := SendPushNotificationRequest{}
	return &this
}

// NewSendPushNotificationRequestWithDefaults instantiates a new SendPushNotificationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendPushNotificationRequestWithDefaults() *SendPushNotificationRequest {
	this := SendPushNotificationRequest{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *SendPushNotificationRequest) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendPushNotificationRequest) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *SendPushNotificationRequest) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *SendPushNotificationRequest) SetTitle(v string) {
	o.Title = &v
}

// GetLink returns the Link field value if set, zero value otherwise.
func (o *SendPushNotificationRequest) GetLink() string {
	if o == nil || o.Link == nil {
		var ret string
		return ret
	}
	return *o.Link
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendPushNotificationRequest) GetLinkOk() (*string, bool) {
	if o == nil || o.Link == nil {
		return nil, false
	}
	return o.Link, true
}

// HasLink returns a boolean if a field has been set.
func (o *SendPushNotificationRequest) HasLink() bool {
	if o != nil && o.Link != nil {
		return true
	}

	return false
}

// SetLink gets a reference to the given string and assigns it to the Link field.
func (o *SendPushNotificationRequest) SetLink(v string) {
	o.Link = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *SendPushNotificationRequest) GetBody() string {
	if o == nil || o.Body == nil {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendPushNotificationRequest) GetBodyOk() (*string, bool) {
	if o == nil || o.Body == nil {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *SendPushNotificationRequest) HasBody() bool {
	if o != nil && o.Body != nil {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *SendPushNotificationRequest) SetBody(v string) {
	o.Body = &v
}

func (o SendPushNotificationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Title != nil {
		toSerialize["title"] = o.Title
	}
	if o.Link != nil {
		toSerialize["link"] = o.Link
	}
	if o.Body != nil {
		toSerialize["body"] = o.Body
	}
	return json.Marshal(toSerialize)
}

type NullableSendPushNotificationRequest struct {
	value *SendPushNotificationRequest
	isSet bool
}

func (v NullableSendPushNotificationRequest) Get() *SendPushNotificationRequest {
	return v.value
}

func (v *NullableSendPushNotificationRequest) Set(val *SendPushNotificationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendPushNotificationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendPushNotificationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendPushNotificationRequest(val *SendPushNotificationRequest) *NullableSendPushNotificationRequest {
	return &NullableSendPushNotificationRequest{value: val, isSet: true}
}

func (v NullableSendPushNotificationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendPushNotificationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


